# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-26 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=255, unique=True, verbose_name='请求ID')),
                ('action_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='动作发生的时间')),
                ('user_id', models.CharField(max_length=255, verbose_name='产生动作的用户')),
                ('message', models.TextField(blank=True, null=True, verbose_name='动作详情描述')),
                ('module', models.IntegerField(choices=[(0, '权限')], verbose_name='动作所在的模块')),
                ('action', models.IntegerField(choices=[(1, '创建'), (2, '修改'), (3, '删除'), (4, '上线'), (5, '下线'), (6, '保存'), (7, '撤回')], verbose_name='动作名称')),
            ],
            options={
                'verbose_name': '操作记录表',
                'db_table': 'logs_operationlog',
            },
        ),
    ]
